name: presenter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/나는포기하지않아.png
    - assets/images/내가만든쿠키.png
    - assets/images/대표캐릭터.png
    - assets/images/빵찾아삼만리.png
    - assets/images/커피는내친구.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900